### ISSUE TITLE
Using LLaVA Plus?/

### ISSUE THREAD

**Issue by shersoni610** [LLaVA-VL/LLaVA-Interactive-Demo#7]
Hello,

Does this code use LLaVAplus ?

thaks

**Comment by ChunyuanLI** [comment]
No. LLaVA-Interactive and LLaVA-Plus are independent at this moment. 

LLaVA-Interactive employs LLaVA-1.5 for visual chat. It is a demo that combines three existing vision-language models without anything training.

In LLaVA-Interactive, the tools/skills are manually selected by the humans, and tool execution results are directly presented to humans; In LLaVA-Plus, the tools/skills are automatically selected by LMM and the tool execution results are further aggregated by the LMM to present to humans.

**Comment by mattmazzola** [comment]
Given there has not been any more activity on this issue and Chunyuan's response from many months ago, I assume the question has been answered sufficiently and the issue can be closed.
